### ISSUE TITLE
Corrigir escolha do gênero da palavra escolhida

### ISSUE THREAD

**Issue by bartier** [bartier/safadeza-generator#1]
O bot faz uma verificação simples para verificar o genêro da palavra escolhida:
Se termina com a é feminino, caso contrário masculino
![image](https://user-images.githubusercontent.com/18057391/66724437-7d39eb00-edfc-11e9-978a-68f2e08cdd90.png)

Causando erros como o abaixo:
![image](https://user-images.githubusercontent.com/18057391/66724426-5da2c280-edfc-11e9-90e5-221dd7fc81e8.png)

Seria interessante consumir uma API de dicionário online, por exemplo, http://dicio.com/ para verificar o genêro e obter uma frase mais coerente.

**Comment by wenneton** [comment]
Tentando resolver a issue utilizando a biblioteca Dicio em Python

**Comment by wenneton** [comment]
Tentando resolver a issue utilizando a biblioteca Dicio

**Comment by bartier** [comment]
@wenneton Show, manda bala! Qualquer coisa estou a disposição.
