### ISSUE TITLE
[Sugestão de melhoria] Tratar as palavras no plural para escolher artigo correto 

### ISSUE THREAD

**Issue by bartier** [bartier/safadeza-generator#3]
Conforme indicado no PR #2:

Sugestão de melhoria: Remover as palavras que terminam com 's' (plurais) ou encontrar uma maneira de mudar o artigo antes destas palavras.

Irei deixar aberto essa issue para verificar posteriormente. Caso alguém tenha algo a acrescentar algo sinta-se à vontade.

**Comment by igor-simoes** [comment]
Olá, eu posso tentar corrigir isso hoje

**Comment by bartier** [comment]
@igor-simoes Olá, tudo bem? Pode sim. Você irá pelo caminho de verificar uma maneira de mudar o artigo antes destas palavras ou com a remoção de palavras que terminam com 's' (plurais)?

**Comment by bartier** [comment]
Pessoal, uma atualização a respeito dessa issue:

Acredito que seja mais vantajoso a opção de identificar as palavras nos plural e mudar o artigo, assim não perdemos em 'combinações', o que acham?

**Comment by igor-simoes** [comment]
Olá @bartier, eu iria realizar 2 PRs para resolver as 2 opções, mas eu posso trabalhar nessa melhoria para escolher o artigo correto.

**Comment by bartier** [comment]
@igor-simoes Perfeito, acredito que a opção da escolha do artigo correto é a melhor, sem dúvidas é mais desafiador, porém mais recompensador. A opção de remover as palavras seria, ao meu ver, uma forma de 'acobertar' o problema.

Caso tenha alguma dúvida quanto a implementação permaneço a disposição. Imagino que, os passos abaixo possam resumir o que seria o ideal:

1. Identificar que a palavra está no plural
2. Obter a palavra no singular da palavra 'principal
3. Pesquisar usando a api do Dicio() para verificar no dicionário online o gênero
4. Definir o artigo com o gênero + 's' do plural

Acredito que o caminho seja esse, mas eu pensei rapidamente a respeito. Fique à vontade para implementar o que achar melhor =]

**Comment by bartier** [comment]
Conforme #12 essa issue será encerrada
