### ISSUE TITLE
[Refatoração] Arquivo utils.py

### ISSUE THREAD

**Issue by bartier** [bartier/safadeza-generator#5]
Pessoal, tudo bem? :)

Acredito que possa ser feito uma refatoração no arquivo [utils.py](https://github.com/bartier/safadeza-generator/blob/master/utils.py). Ele foi gerado rapidamente apenas para gerar o arquivo de palavras que não possui verbos [com base nesse arquivo](https://github.com/bartier/safadeza-generator/blob/master/palavras.txt). No caso, foi pego o output dele  via terminal e adicionado em um arquivo. Algo assim:
```
python utils.py > arquivo_saida.txt
```

Penso que o melhor seria passar o nome do arquivo do arquivo que ele vai consumir e do arquivo
que ele deva gerar (via sys.argv, por exemplo). Assim, ele percorreira o arquivo a ser consumido verificando se a a palavra não é um verbo, se ela não é um verbo, ela deve aparecer no arquivo de "saída". 

Penso até que o nome desse script deve ser mudado, na correria ficou "utils.py".

Sintam-se à vontade para sugerir/discutir esse tipo de refatoração. Caso alguém tenha interesse em pegar essa Issue só avisar :) 

*ps: antes de começar algum trabalho é uma boa prática avisar o que pensa em implementar/discutir na issue, conforme dito no README, você corre o risco de perder muito tempo em um trabalho que pode não ser aceito caso não esteja dentre o esperado do projeto.*

**Comment by rrbarioni** [comment]
Olá,

Olhei o código em utils.py, eu sugiro algumas mudanças:
- Em relação aos argumentos do script, seria interessante usar _argparse_, fica mais organizado;
- O uso da função _endwith_ em _strings_ pode receber uma tupla também (no caso, nem precisa repetir o _if_ para cada uma das possibilidades de término de verbo;
- O uso das funções _lower()_ e _rstrip()_ também podem ser executados uma única vez no código, sem precisar repetí-lo.

Em relação a desempenho, potencialmente o gargalo seria de leitura/escrita do arquivo; para a leitura, dá pra utilizar o _.read().splitlines()_, o qual lerá todo o arquivo de entrada de uma só vez. Já para a escrita no arquivo de saída, não sei do processo mais otimizado.

Vou subir um PR, fica a vontade pra sugerir mudanças.

**Comment by bartier** [comment]
@rrbarioni Acredito que esses pontos que você colocou seja o caminho mesmo, eles fazem sentido. Obrigado por pontuá-los! Sendo assim, fico no aguardo do PR para code review =]

**Comment by bartier** [comment]
Irei fechar essa issue visto que @rrbarioni realizou as alterações no PR #7
