### ISSUE TITLE
Censurar palavras e verbos improprios

### ISSUE THREAD

**Issue by bartier** [bartier/safadeza-generator#8]
O titulo e bem direto, quem quiser estou aceitando PR que remova coisas que podem dar problema.

**Comment by bartier** [comment]
Arquivos em questão: verbos.txt e palavras_sem_verbos.txt

**Comment by brunoliberal** [comment]
Vou dar uma olhada.
Remover as palavras proibidas de ambos os arquivos ajuda?

**Comment by bartier** [comment]
Sim @brunoliberal, os arquivos indicados são os comentados anteriormente:

verbos.txt
palavras_sem_verbos.txt

Acredito que o foco seja no verbos.txt para remover verbos de assédio (eu ja tirei os principais por exemplo, esquartejar)

**Comment by brunoliberal** [comment]
trabalhando no PR https://github.com/bartier/safadeza-generator/pull/13
